### ISSUE TITLE
Cannot filter by email addresses

### ISSUE THREAD

**Issue by spdaly** [brpx/node-sequelize-querystring#1]
The regex in the find method doesn't allow email addresses as values.  It only returns the user portion, not the @domain.com.

**Comment by ricmalta** [comment]
I @spdaly.
That's actually true. I'll fix it!
```
AssertionError: expected { email: { '$eq': 'ricardo' } } to have a deep property 'email.$eq' of 'ricardo@brpx.com', but got 'ricardo'
```
Thank you for the report!
