### ISSUE TITLE
Nested queries without include?

### ISSUE THREAD

**Issue by tloriato** [brpx/node-sequelize-querystring#10]
I can't seem to make a simple nested where to work without including the respective Model which should be filtered. 

`myForeignKey.propertyOfTheModel eq Something` isn't working.

**Comment by ricmalta** [comment]
TL;DR Its implemented just for actual table rows

Sorry @tloriato, probably this message is now useless. However, at this point this module is tooling to convert a query string into a sequelize sql query to actual table rows.

**Comment by tloriato** [comment]
I don't recall my situation exactly, but it's alright. Thanks, Ricardo!
