### ISSUE TITLE
% for 'like' operator

### ISSUE THREAD

**Issue by maxim-danilov** [brpx/node-sequelize-querystring#11]
Hi! :)
Thank you for this package. The Internet really needs the node-sequelize-querystring tool.

    "sequelize-querystring": "^0.10.0",

`?filter=name eq showme // works properly`

However:
```
?filter=name like %  // ?got an empty where clause
?filter=name like showme%  // ?got an empty where clause
?filter=name like 'showme%'  // ?got an empty where clause
?filter=name like "showme%" // ?got an empty where clause
```

Is there any way to use %?

Thank you :)

**Comment by chornos13** [comment]
maybe you want something more customizable like https://github.com/chornos13/sequelice-query :)

**Comment by ricmalta** [comment]
@maxim-danilov In my opinion that approach could result in a vulnerability by using the % in a like operator directly from the frontend to the SQL. 
I would suggest you to implement that in the backend by controlling the input correctly. 

Too much magic could end up in a DDoS or even SQL injection.

**Comment by maxim-danilov** [comment]
Actually, this package supports the like operator. Just need to encode % sings:
?filter=email%20iLike%20%25substring%25 :clap:
