### ISSUE TITLE
like can not be used to define 'starts with' or 'ends with' patterns

### ISSUE THREAD

**Issue by mfernandes-git** [brpx/node-sequelize-querystring#2]
Hello Ricardo !

I am using "sequelize-querystring": "0.7.6"

Using the following data
```
name = ricardo
name = mark
name = fake ricardo
```
I would like to use the query string  "name like ricardo%" to return only 'ricardo'.  I don't want it to return 'ricardo' and 'fake ricardo'.

This is not possible because sequelize-querystring always wraps the like value inside %.

I would expect to use a pattern to define the like value.  If no pattern is defined for the like value, like is treated as equals.

See the PostgreSQL documentation for like
https://www.postgresql.org/docs/9.0/static/functions-matching.html

What do you think?

**Comment by ricmalta** [comment]
Hi Mark!
I think I made a nice hack back when I wrote that code :)
I'll fix this to support a proper string match and wildcards.

Expect a newer version.

Thanks

**Comment by mfernandes-git** [comment]
The problem is a little more complicated than I thought.
In fact we can not use % or _ inside the like value.  
The regular expression used to capture the value does not support this.

In example for the query string 'name like r_card%'
generates
'name.$like' 
'r'

**Comment by ricmalta** [comment]
Try to upgrade to the version 0.8.0.
Probably needs some improvements to support full wildcards and regexp.

If possible, just create a butch of unit tests that demonstrate the examples you just showed. This will help me with the problem interpretation. Do a pull request with those tests, please

**Comment by mfernandes-git** [comment]
Thank you for the quick release!  I have created a pull request to support the _ wildcard.  The pull request also has the unit tests you asked for.

Thanks again.

**Comment by ricmalta** [comment]
Hi @mfernandes-git 
I will have a look as soon as possible. 

The new release have worked for you?

**Comment by mfernandes-git** [comment]
The new release works perfectly for me.

**Comment by ricmalta** [comment]
The merge is done.

Thanks for the help 👍
