### ISSUE TITLE
and, or, between, not between

### ISSUE THREAD

**Issue by hagen** [brpx/node-sequelize-querystring#5]
Have you had any more thoughts on these? I'm using this module, and have already started cutting enhancements I need - Symbol operators for one.
If you have thoughts on how you'd like the 'coming soon' features implemented, let me know as I'm working on it any way.

Also, the use of comma-separated ANDs isn't going to work long term, I don't think. Firstly, it leaves no room for ORs. Would you consider a more OData style filter query (and parser)?

**Comment by ricmalta** [comment]
Hi @hagen,
Sorry about my late response. Recently @dt-rush changed the operators implementation. Honestly, right now I'm not familiarized with the new symbols operators on the sequelize, so I'm afraid I can't help you adding the AND operators right now. Unfortunately OR is the only operator implemented by using the comma separated conditions.

I suggest you to do a pull request with a solution proposal. Is that ok to you?

Can try to implement this in my free time in the next couple of weeks too.

**Comment by itajenglish** [comment]
@ricmalta When I use comma separated values it queries using AND. Is there a way for it to query using OR?

**Comment by ricmalta** [comment]
@hagen @itajenglish This a real limitation. How did you suggest to implement the OR and AND operators instead of just coma (,) to do an AND?

Feel free to suggest implementation or just start a draft pull request to discuss the implementation there.

I'm afraid that whatever the solution is, will be a breakable one. However this is not a problem as long as proper versioning.

**Comment by hagen** [comment]
Have moved to [odata-sequelize](https://www.npmjs.com/package/odata-sequelize) now.
For me it made sense to leverage the OData standard, although odata-sequelize doesn't support all operators. Check it out for inspiration. Query string parsing is handled by [odata-parser](https://www.npmjs.com/package/odata-parser).

Appreciate this might not be the kind of constructive feedback you probably need, but that's where I headed to solve that issue.
