### ISSUE TITLE
String based operators are now deprecated

### ISSUE THREAD

**Issue by dt-rush** [brpx/node-sequelize-querystring#6]
Sequelize now warns of [deprecation for the string-based operators](http://docs.sequelizejs.com/manual/tutorial/querying.html#operators) used in queries in this package (eg. `$lt`). We should support users who wish to migrate to Sequelize symbol operators.

The naive solution is:

1. Importing sequelize (therefore adding it as a dependency) to access `sequelize.Op` constants.

However sequelize uses ES6's `Symbol`, so the version of each symbol from our sequelize is not going to be the same as that of the user's sequelize.

Thus, I propose we add the following use pattern if the user desires to use `Sequelize.Op`, in which the user supplies their `Op` object:

```
const Op = require('sequelize').Op;
const sqs = require('sequelize-querystring').symbolicOp(Op);
```

This changes the code in this repo to a pattern like:

```
'gt': { op: (symbolic ? [Op.gt] : '$gt'), val: defaultValue },
```

I'll shortly submit a PR along these lines.

**Comment by dt-rush** [comment]
WOW I'm a goof, I didn't realize they were using es6's `Symbol`. That makes things a lot simpler. We can just use the pattern:

```
const sqs = require('sequelize-querystring').symbolic;
```

... where we export an object `symbolic` which wraps the main behaviour by setting `symbolic = true`. We would still internally use:

```
'gt': { op: (symbolic ? [Op.gt] : '$gt'), val: defaultValue },
```

**Comment by dt-rush** [comment]
Actually we already take a sequelize object in `sort()`, so I'll just generalize this to a Parser class taking the sequelize object of the user.

**Comment by dt-rush** [comment]
The final pattern I implemented is the cleanest:

```
const sequelize = require('sequelize');

// do things with sequelize, like create models, call .sync(), etc...

const sqs = require('sequelize-querystring').withSymbolicOps(sequelize);
```

**Comment by dt-rush** [comment]
`const sqs = require('sequelize-querystring')` still works identically as before. Since the API has not changed and it's backwards-compatible, I flagged it as `Change-Type: minor`, and modified `package.json` to `0.9.0`.

**Comment by ricmalta** [comment]
Hi @dt-rush, sorry about the late response and thanks you for the help!
